### PR TITLE
Backwards-compatibility for python 3.5+

### PR DESCRIPTION
**Pull request by asmodai27**
Hit an import error when using an updated version of this script on my setup (running python 3.6):
```
Traceback (most recent call last):
  File "~/.cache/pre-commit/repo6tcjuqfw/clang_format.py", line 23, in <module>
    from typing import Final, Mapping, Optional, Sequence, Tuple
ImportError: cannot import name 'Final'
```

Found out that `Final` was added to typing v3.8, only available for python 3.7+, but was actually backported in `typing_extensions` for  python 3.5 and 3.6 (see [the module's page](https://pypi.org/project/typing-extensions/) for more details).
So, here is a quick fix for that.

### CODE REVIEW

**Comment by jlebar** [comment]
This now changes the problem from "doesn't work with python 3.5" to "with python 3.5 you have to pip install typing_extensions".  I guess that's better, but at some point this project should actually have real Python dependency management.

Thank you for the fix.
